In [31]:
import numpy as np

# Create random vector of size 20 with float values between 1 and 20
x = np.random.uniform(1, 20, 20)

# Reshape array to 4 by 5
matrix = x.reshape(4, 5)
print(matrix)

# Replace max in each row by 0 using np.where()
matrix = np.where(matrix == np.max(matrix, axis=1, keepdims=True), 0, matrix)

# Print the matrix
print(matrix)



[[18.06672346  6.2791238   9.13341567 17.62172514  3.30293502]
 [19.7508902  18.72172324  8.73043107  5.53046589 15.41505401]
 [ 4.26153766  4.12398094  2.24679742 17.76086411  9.87426075]
 [13.05952928 14.09513447  1.89420172  2.87942956 16.7941825 ]]
[[ 0.          6.2791238   9.13341567 17.62172514  3.30293502]
 [ 0.         18.72172324  8.73043107  5.53046589 15.41505401]
 [ 4.26153766  4.12398094  2.24679742  0.          9.87426075]
 [13.05952928 14.09513447  1.89420172  2.87942956  0.        ]]
